### ISSUE TITLE
RK3399 armbian ( ubuntu 22.04 ) 运行虚拟机报错

### ISSUE THREAD

**Issue by jzhou404** [unifreq/openwrt_packit#127]
板子是Nanopc-t4, 

故障log, 请指教一下，谢谢

Unable to complete install: 'internal error: process exited while connecting to monitor: 2022-09-15T00:42:23.951128Z qemu-system-aarch64: kvm_init_vcpu: kvm_arch_init_vcpu failed (0): Invalid argument'

Traceback (most recent call last):
  File "/usr/share/virt-manager/virtManager/asyncjob.py", line 72, in cb_wrapper
    callback(asyncjob, *args, **kwargs)
  File "/usr/share/virt-manager/virtManager/createvm.py", line 2008, in _do_async_install
    installer.start_install(guest, meter=meter)
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 695, in start_install
    domain = self._create_guest(
  File "/usr/share/virt-manager/virtinst/install/installer.py", line 637, in _create_guest
    domain = self.conn.createXML(initial_xml or final_xml, 0)
  File "/usr/lib/python3/dist-packages/libvirt.py", line 4400, in createXML
    raise libvirtError('virDomainCreateXML() failed')
  libvirt.libvirtError: internal error: process exited while connecting to monitor: 2022-09-15T00:42:23.951128Z qemu-system-aarch64:   kvm_init_vcpu: kvm_arch_init_vcpu failed (0): Invalid argument

**Comment by xiaohong001** [comment]
3399是4小核+2大核，在启动前需要在xml中配置一下，我这个是配置2核的例子，大小核不能同时配置
```
<vcpu placement='static' cpuset='0-1'>2</vcpu>
<cputune>
  <vcpupin vcpu='0' cpuset='0'/>
  <vcpupin vcpu='1' cpuset='1'/>
  <emulatorpin cpuset='0-1'/>
</cputune>
```
